import { ReportCardLanguage } from "@/lib/report-card-types";

export function reportCardLabels(language: ReportCardLanguage) {
  if (language === "en") {
    return {
      reportTitle: "Student Report Card",
      schoolCode: "School Code",
      generatedOn: "Generated on",
      publishedOn: "Published on",
      student: "Student",
      studentCode: "Student Code",
      class: "Class",
      period: "Period",
      overallAverage: "Overall Average",
      rank: "Rank",
      inSection: "in section",
      decision: "Decision",
      subject: "Subject",
      coefficient: "Coefficient",
      average: "Average",
      appreciation: "Comment",
      attendance: "Attendance",
      attendancePlaceholder:
        "Attendance summary will be integrated in a future version.",
      conduct: "Conduct / General Comment",
      noConduct: "No general comment entered yet.",
      teacherComment: "Teacher Comment",
      directorComment: "Director Comment",
      finalRemarks: "Final Remarks",
      teacher: "Teacher",
      direction: "School Direction",
      parent: "Parent / Guardian",
      noSubjectResults: "No subject results found.",
      admitted: "Passed",
      watch: "Needs attention",
      pending: "To be determined",
      excellent: "Excellent",
      veryGood: "Very good",
      good: "Good",
      passing: "Passing",
      insufficient: "Insufficient",
      scale: "out of 20",
    };
  }

  return {
    reportTitle: "Bulletin scolaire",
    schoolCode: "Code école",
    generatedOn: "Généré le",
    publishedOn: "Publié le",
    student: "Élève",
    studentCode: "Code élève",
    class: "Classe",
    period: "Période",
    overallAverage: "Moyenne générale",
    rank: "Rang",
    inSection: "dans la section",
    decision: "Décision",
    subject: "Matière",
    coefficient: "Coefficient",
    average: "Moyenne",
    appreciation: "Appréciation",
    attendance: "Assiduité",
    attendancePlaceholder:
      "Résumé d’assiduité à intégrer dans une prochaine version.",
    conduct: "Conduite / Appréciation générale",
    noConduct: "Aucune appréciation saisie pour le moment.",
    teacherComment: "Commentaire de l’enseignant",
    directorComment: "Commentaire de la direction",
    finalRemarks: "Remarques finales",
    teacher: "Enseignant",
    direction: "Direction",
    parent: "Parent / Responsable",
    noSubjectResults: "Aucun résultat de matière trouvé.",
    admitted: "Admis",
    watch: "À surveiller",
    pending: "À déterminer",
    excellent: "Excellent",
    veryGood: "Très bien",
    good: "Bien",
    passing: "Passable",
    insufficient: "Insuffisant",
    scale: "sur 20",
  };
}