import { ReportCardLanguage } from "@/lib/report-card-types";

export function reportCardLabels(language: ReportCardLanguage) {
  if (language === "en") {
    return {
      reportTitle: "Student Report Card",
      schoolCode: "School Code",
      generatedOn: "Generated on",
      publishedOn: "Published on",
      student: "Student",
      studentCode: "Student Code",
      class: "Class",
      period: "Period",
      overallAverage: "Overall Average",
      rank: "Rank",
      inSection: "in section",
      decision: "Decision",
      subject: "Subject",
      coefficient: "Coefficient",
      average: "Average",
      appreciation: "Comment",
      attendance: "Attendance",
      attendancePlaceholder:
        "Attendance summary will be integrated in a future version.",
      conduct: "Conduct / General Comment",
      noConduct: "No general comment entered yet.",
      teacher: "Teacher",
      direction: "School Direction",
      parent: "Parent / Guardian",
      noSubjectResults: "No subject results found.",
      admitted: "Passed",
      watch: "Needs attention",
      pending: "To be determined",
      excellent: "Excellent",
      veryGood: "Very good",
      good: "Good",
      passing: "Passing",
      insufficient: "Insufficient",
      scale: "out of 20",
    };
  }

  return {
    reportTitle: "Bulletin scolaire",
    schoolCode: "Code ecole",
    generatedOn: "Genere le",
    publishedOn: "Publie le",
    student: "Eleve",
    studentCode: "Code eleve",
    class: "Classe",
    period: "Periode",
    overallAverage: "Moyenne generale",
    rank: "Rang",
    inSection: "dans la section",
    decision: "Decision",
    subject: "Matiere",
    coefficient: "Coefficient",
    average: "Moyenne",
    appreciation: "Appreciation",
    attendance: "Assiduite",
    attendancePlaceholder:
      "Resume d'assiduite a integrer dans une prochaine version.",
    conduct: "Conduite / Appreciation generale",
    noConduct: "Aucune appreciation saisie pour le moment.",
    teacher: "Enseignant",
    direction: "Direction",
    parent: "Parent / Responsable",
    noSubjectResults: "Aucun resultat de matiere trouve.",
    admitted: "Admis",
    watch: "A surveiller",
    pending: "A determiner",
    excellent: "Excellent",
    veryGood: "Tres bien",
    good: "Bien",
    passing: "Passable",
    insufficient: "Insuffisant",
    scale: "sur 20",
  };
}
